# Site settings
description: "A PHP library inspired by the LINQ 2 Objects extension methods in .NET."
baseurl: "/linq"
url: "http://fusonic.github.io/linq"
github_username: fusonic
github_repository: linq
version: 1.0.0

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
extensions: [fenced_code_blocks]
sass:
  sass_dir: _sass
  style: :compressed
